spring:

  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"

  jpa:
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5433/avansas
    username: postgres
    password: superpassword
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

application:
  jwt:
    key: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14